### ISSUE TITLE
movesort.cpp第134行到141行

### ISSUE THREAD

**Issue by peteryuanpan** [xqbase/eleeye#3]
// 2. MVV(LVA)启发，可能要循环若干次；
  case PHASE_GOODCAP:
    if (nMoveIndex < nMoveNum && mvs[nMoveIndex].wvl > 1) {
      // 注意：MVV(LVA)值不超过1，则说明吃子不是直接能获得优势的，这些着法将留在以后搜索
      nMoveIndex ++;
      __ASSERT_PIECE(pos.ucpcSquares[DST(mvs[nMoveIndex - 1].wmv)]);
      return mvs[nMoveIndex - 1].wmv;
    }

我认为应该改成这样：

  // 2. MVV(LVA)启发，可能要循环若干次；
  case PHASE_GOODCAP:
    if (nMoveIndex < nMoveNum && mvs[nMoveIndex].wvl > 1) {
      // 注意：MVV(LVA)值不超过1，则说明吃子不是直接能获得优势的，这些着法将留在以后搜索
      nMoveIndex ++;
      __ASSERT_PIECE(pos.ucpcSquares[DST(mvs[nMoveIndex - 1].wmv)]);
      return mvs[nMoveIndex - 1].wmv;
    }
   else {
        nPhase = PHASE_KILLER1;
    }

否则 NextFull函数永远不会跑到 case PHASE_KILLER1 部分，也自然不会跑到后面的 case PHASE_KILLER2，case PHASE_GEN_NONCAP，case PHASE_REST等部分。。

**Comment by auntyellow** [comment]
有没有理解这一行？
// 技巧：这里没有"break"，表示"switch"的上一个"case"执行完后紧接着做下一个"case"，下同
