### ISSUE TITLE
为什么空着裁剪那么厉害？

### ISSUE THREAD

**Issue by peteryuanpan** [xqbase/eleeye#7]
我把你们search.cpp中的空着裁剪打了注释，同样让引擎搜10个局面，每个都只搜1秒。
我发现有空着裁剪比没有空着裁剪要多搜2层！
有空着裁剪时，1s可平均搜9层，没有只能搜7层

之后，我在自己的引擎上尝试了下空着裁剪，搜索层次大大提升，而且没有搜挂

我百思不得其解，为什么？你们能为我解答一下吗？多谢
空着裁剪的一个条件是要当前局面的分数不小于200分，但这种局面很多吗？为什么会裁剪得那么厉害？

**Comment by auntyellow** [comment]
Null-Move和Quiescence一样，可以大幅削减水平线效应

**Comment by peteryuanpan** [comment]
http://www.xqbase.com/computer/advanced_nullmove.htm
我读了这个，虽然不是完全明白，但是大致懂了，多谢！
